[project]
name = "paligemma-ft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dynamonda", email = "v7gj9kk@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "ollama>=0.6.3",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.4",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[project.scripts]
paligemma-ft = "paligemma_ft:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
